stage: 2

loss_type: soft_cam_associate
#train configs
num_iter: 150
max_epoch: 90
use_id_loss: True

#train
resume_path: b/checkpoints/stage1/train_2_epoch_50.pth

#path
logs_dir: /logs/stage2/
model_dir: /checkpoints/stage2/

use_soft: True
use_corr: False
cdc: False
use_tree: False
otpm: True
ncmu: False
